cache:
  directories:
    - node_modules
install:
  - 'npm install'
language: node_js
node_js:
  - stable
  - node
script:
  - 'npm run test'
services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
  - npm run create-tables
