cache:
  directories:
    - node_modules
install:
  - 'npm install'
language: node_js
node_js:
  - stable
  - node
script:
  - 'npm run test'
  - npm run coveralls
  - nyc --reporter=lcov npm run unit
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - npm install nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
env:
  global:
    - CC_TEST_REPORTER_ID=CC_REPORTER_ID
notifications:
  email: false
