cache:
  directories:
    - node_modules
install:
  - 'npm install'
language: node_js
node_js:
  - stable
  - node
script:
  - 'npm run test'
  - npm run coveralls
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - npm install codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter  < ./coverage/lcov.info
env:
  global:
    - CODECLIMATE_REPO_TOKEN=CC_REPO_TOKEN
